# Generated by Django 4.0.3 on 2022-09-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_answer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_answer',
            field=models.BooleanField(default=False),
        ),
    ]
