# Generated by Django 4.1 on 2022-09-09 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_upvotepost_upvoteanswer_followuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvotepost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='upvotepost',
            name='user',
        ),
        migrations.DeleteModel(
            name='UpvoteAnswer',
        ),
        migrations.DeleteModel(
            name='UpvotePost',
        ),
    ]
